/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_OpenGLBridge */

#ifndef _Included_jni_OpenGLBridge
#define _Included_jni_OpenGLBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_OpenGLBridge
 * Method:    sendData
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[IILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jni_OpenGLBridge_sendData
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jintArray, jint, jstring, jstring);

/*
 * Class:     jni_OpenGLBridge
 * Method:    openWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_OpenGLBridge_openWindow
  (JNIEnv *, jclass);

/*
 * Class:     jni_OpenGLBridge
 * Method:    moveCamera
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_jni_OpenGLBridge_moveCamera
  (JNIEnv *, jclass, jfloat);

#ifdef __cplusplus
}
#endif
#endif
